[package]
cairo-version = "=2.9.2"
name = "market"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[tool.fmt]
sort-module-level-items = true

[dependencies]
starknet = "2.9.2"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.20.0" }

[dev-dependencies]
cairo_test = "=2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.1" }

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = ["dojo::world::world_contract::world"]


[profile.sepolia]

[features]
default = []
